[workspace]
name = "nwsrfs-hydro-autocalibration"
channels = ["conda-forge"]
platforms = ["osx-arm64","linux-64"]
version = "0.1.0"

[tasks]
setup = "Rscript -e \"source('setup.R')\""

[dependencies]
hdf5 = ">=1.14.6,<2"
gdal = ">=3.12.2,<4"
c-compiler = ">=1.11.0,<2"
cxx-compiler = ">=1.11.0,<2"